[REF] Fixing bugs.

diff --git a/debian/prerm b/debian/prerm
--- a/debian/prerm
+++ b/debian/prerm
@@ -25,16 +25,16 @@
 set -e
 
 # summary of how this script can be called:
-#        * <postinst> `configure' <most-recently-configured-version>
-#        * <old-postinst> `abort-upgrade' <new version>
-#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
-#          <new-version>
-#        * <postinst> `abort-remove'
-#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
-#          <failed-install-package> <version> `removing'
+#        * <prerm> `remove'
+#        * <old-prerm> `upgrade' <new-version>
+#        * <new-prerm> `failed-upgrade' <old-version>
+#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
+#        * <deconfigured's-prerm> `deconfigure' `in-favour'
+#          <package-being-installed> <version> `removing'
 #          <conflicting-package> <version>
 # for details, see https://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
+
 
 function echospaced() {
     printf "\n# %s\n" "${1}"
@@ -44,7 +44,7 @@ SHAREDIR="/usr/share/mash"
 ICONSIZES="16 22 32 48 64 128 256 512"
 
 case "$1" in
-    configure)
+    remove|upgrade|deconfigure)
       echospaced "Uninstalling icons ..."
       for SIZE in ${ICONSIZES}; do
           xdg-icon-resource uninstall --size "${SIZE}" --theme "hicolor" \
@@ -58,11 +58,11 @@ case "$1" in
       xdg-desktop-menu uninstall --mode "system" "${SHAREDIR}/collagelabs-mash.desktop"
     ;;
 
-    abort-upgrade|abort-remove|abort-deconfigure)
+    failed-upgrade)
     ;;
 
     *)
-        echo "postinst called with unknown argument \`$1'" >&2
+        echo "prerm called with unknown argument \`$1'" >&2
         exit 1
     ;;
 esac
